services:
  wordpress:
    image: wordpress:6.5-php8.2-apache
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: Wp@12345!
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./ai-wp:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: Wp@12345!
    volumes:
      - db_data:/var/lib/mysql

  react-app:
    build:
      context: ./ai-react
    ports:
      - "3000:80"
    depends_on:
      - wordpress

volumes:
  db_data: 
